// Password reset email — sent when the user requests a reset from
// the /forgot-password page (v0.76+).
//
// The link is generated by Better Auth and is single-use, short-
// lived (default 1h). We just pass it through unchanged.

import {
  renderEmailLayout,
  renderEmailText,
  type EmailLayoutOptions,
} from "./_shared";

interface Args {
  name?: string | null;
  /** Pre-built reset URL from Better Auth. */
  link: string;
}

export function passwordResetEmail(args: Args): {
  subject: string;
  html: string;
  text: string;
} {
  const greet = args.name?.trim() ? args.name.trim() : "there";
  const opts: EmailLayoutOptions = {
    heading: "Reset your password",
    paragraphs: [
      `Hi ${greet} — we got a request to reset your CodeTrawl password.`,
      `Click the button below to set a new one. The link is valid for 1 hour.`,
    ],
    cta: { label: "Reset password", href: args.link },
    footnote:
      "If you didn't ask to reset your password, you can ignore this email — your current password stays unchanged. If you keep seeing reset emails you didn't request, reach out via the feedback form so we can investigate.",
  };
  return {
    subject: "Reset your CodeTrawl password",
    html: renderEmailLayout(opts),
    text: renderEmailText(opts),
  };
}
