// Verification email — sent after signup so the user can confirm
// they own the email address they gave us (v0.76+).
//
// The link is generated by Better Auth and is single-use, short-
// lived (default 24h). We just pass it through unchanged.

import {
  renderEmailLayout,
  renderEmailText,
  type EmailLayoutOptions,
} from "./_shared";

interface Args {
  /** Display name from the user record. Falls back to "there" when
   *  the user signed up via email-only without a name field. */
  name?: string | null;
  /** Pre-built verification URL from Better Auth. Contains the
   *  signed token + the path our app uses to land the user. */
  link: string;
}

export function verificationEmail(args: Args): {
  subject: string;
  html: string;
  text: string;
} {
  const greet = args.name?.trim() ? args.name.trim() : "there";
  const opts: EmailLayoutOptions = {
    heading: "Confirm your email",
    paragraphs: [
      `Hi ${greet} — welcome to RepoJury.`,
      `Click the button below to confirm this is your email address. The link is valid for 24 hours.`,
    ],
    cta: { label: "Confirm email", href: args.link },
    footnote:
      "If you didn't sign up for RepoJury, you can safely ignore this email — no account was created without confirmation.",
  };
  return {
    subject: "Confirm your RepoJury email",
    html: renderEmailLayout(opts),
    text: renderEmailText(opts),
  };
}
